name: Compile LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache LaTeX
      uses: actions/cache@v2
      with:
        path: /usr/local/texlive
        key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-texlive-

    - name: Install LaTeX
      if: steps.cache.outputs.cache-hit != 'true'
      run: sudo apt-get update && sudo apt-get install --fix-missing texlive-full

    - name: Compile LaTeX Document
      run: pdflatex -interaction=nonstopmode document.tex

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-document
        path: ./document.pdf