name: Compile LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COMMIT_MSG: ${{ github.event.head_commit.message }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-basic

    - name: Compile LaTeX Document
      run: pdflatex -interaction=nonstopmode document.tex

    - name: Delete old tag
      uses: ClementTsang/delete-tag-and-release@v0.4.0
      with:
        delete_release: false
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: latest
        message: Latest build

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: Latest Build
        body: ${{ env.COMMIT_MSG }}

