name: Compile LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COMMIT_MSG: ${{ github.event.head_commit.message }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-basic

    - name: Compile LaTeX Document
      run: pdflatex -interaction=nonstopmode document.tex

    - uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: latest
        tag_exists_error: false
        force_push_tag: true
        no_verify_tag: true
        message: Latest build

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: Latest Build
        body: ${{ env.COMMIT_MSG }}

