name: Compile LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-basic

    - name: Compile LaTeX Document
      run: pdflatex -interaction=nonstopmode document.tex

    - name: Delete old tag
      uses: ClementTsang/delete-tag-and-release@v0.4.0
      with:
        delete_release: true
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: latest
        message: Latest build

    - name: Create GitHub release
      uses: shogo82148/actions-create-release@v1
      with:
        tag_name: latest
        release_name: Latest Build
        generate_release_notes: true

    - name: Add PDF to release
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: document.pdf

