name: Compile LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-basic

    - name: Compile LaTeX Document
      run: pdflatex -interaction=nonstopmode document.tex

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-document
        path: ./document.pdf